package com.playtech.ptargame5.web.service;

import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.Assert;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.playtech.ptargame5.web.db.DbAccess;
import com.playtech.ptargame5.web.model.GameResult;

@RestController
public class GameController {

	private static final Logger log = LoggerFactory.getLogger(GameController.class);

	@Autowired
	private DbAccess db;

	@PostMapping("/api/private/game")
	public GameResult addPlayer(@RequestBody GameResult gameResult) {

		log.info("Received game result: " + gameResult);

		Assert.notNull(gameResult.getCorrectAnswers(), "Number of correct answers is required");
		Assert.isNull(gameResult.getGameId(), "Game id will be generated by the server");
		Assert.notNull(gameResult.getQuestionsAttempted(), "Number of questions attemptedis required");
		Assert.notNull(gameResult.getTotalScore(), "Number of questions attemptedis required");
		Assert.hasText(gameResult.getNickname(), "Nickname is required");

		Assert.notNull(db.findPlayer(gameResult.getNickname()), "Nickname not found");

		gameResult.setGameId(UUID.randomUUID().toString());

		db.addGameResult(gameResult);

		log.info("Game result registered successfully: " + gameResult);

		return gameResult;
	}
}
