package com.playtech.ptargame5.web.service;

import java.util.UUID;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.Assert;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.playtech.ptargame5.web.db.DbAccess;
import com.playtech.ptargame5.web.model.GameResult;
import com.playtech.ptargame5.web.model.GameResultAnswer;

@CrossOrigin
@RestController
public class GameController {

	private static final Logger log = LoggerFactory.getLogger(GameController.class);

	@Autowired
	private DbAccess db;

	@PostMapping("/api/private/game")
	public GameResult addGameResult(@RequestBody GameResult gameResult) {

		log.info("Received game result: " + gameResult);

		Assert.notNull(gameResult.getCorrectAnswers(), "Number of correct answers is required");
		Assert.isNull(gameResult.getGameId(), "Game id will be generated by the server");
		Assert.notNull(gameResult.getQuestionsAttempted(), "Number of questions attemptedis required");
		Assert.notNull(gameResult.getTotalScore(), "Number of questions attemptedis required");
		Assert.hasText(gameResult.getNickname(), "Nickname is required");

		Assert.notNull(db.findPlayer(gameResult.getNickname()), "Nickname not found");

		Assert.notNull(gameResult.getAnswers(), "List of answers is required");

		for (GameResultAnswer answer : gameResult.getAnswers()) {

			Assert.hasText(answer.getQuestion(), "Question is required");
			Assert.isTrue(answer.getQuestion().length() < 400, "Question is too long");

			Assert.notNull(answer.getLevel(), "Level is required");

			Assert.hasText(answer.getCategory(), "Category is required");
			Assert.isTrue(answer.getCategory().length() < 40, "Category is too long");

			Assert.notNull(answer.getAnsweredCorrectly(), "Answered correctly is required");

			Assert.hasText(answer.getCorrectAnswer(), "Correct answer is required");
			Assert.isTrue(answer.getCorrectAnswer().length() < 100, "Correct answer is too long");

			Assert.hasText(answer.getPlayerInput(), "Player input is required");
			Assert.isTrue(answer.getPlayerInput().length() < 100, "Player is too long");

			Assert.notNull(answer.getTimeTaken(), "Time taken is required");

		}

		gameResult.setGameId(UUID.randomUUID().toString());

		db.addGameResult(gameResult);

		log.info("Game result registered successfully: " + gameResult);

		return gameResult;
	}
}
